clear; clc; close all;

%% Input parameters:
% mu_C = ...
% cov_C = ...
% zeta_C = ...
% lambda_C = ...
 
% mu_R = ...
% cov_R = ...
% zeta_R = ...
% lambda_R = ...
 
% mu_V = ...
% cov_V = ...
% zeta_V = ...
% lambda_V = ...

%% Generate random numbers for Monte-Carlo simulation
np = 10000;                           % sample size 
C = lognrnd(lambda_C, zeta_C,[np,1]); % random number for C
% R = lognrnd(...);                   % random number for R
% V = lognrnd(...);                   % random number for V

%% Obtain pressure P:
P = 0.5*C.*R.*V.^2;

%% Create historgram of simulated presssure
figure(1);
histogram(P, 'NumBins', 100, 'Normalization', 'pdf');
box on; grid on;
xlabel('Pressure (lb/ft^2)')
ylabel('PDF');
set(gca,'FontSize',14);
p8a = 'See figure 1'

%% Fit a lognormal distribution to P
p8b = fitdist(P,'lognormal')

%% Compute probability of pressure > 30
% p8c = ...